meta.yml
meta_product_name: "Eat4Good"
meta_title: "Eat4Good - Input your meals and get your real impact on saving hearth by changing step by step your habits"
meta_description: "Each meal is registrer and give you a daily analysis. You earn badges through growing up in veggie world. As motivation is always better together challenge your friends. No idea of veggie food: we propose you a selection to inspire you"
meta_image: "logo.svg" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
